def num1(request):
	return HttpResponse('/num1/xxx')
def num2(request):
	return HttpResponse('/num2/xx')
def num3(request):
	return HttpResponse('/num3/xxx')
def num4(request):
	return HttpResponse('/num4/xxx')
def num5(resquest):
	return HttpResponse('/num5/xxx')
